

<form method="POST" enctype="multipart/form-data" accept-charset="utf-8"  autocomplete="off" class="login">
  <label class="loginLabel" for="login">Login</label>
  <input class="loginInput text" type="text" id="login" name="login" />

  <label class="loginLabel" for="password">Password</label>
  <input class="loginInput password" type="password" id="password" name="password" />
  <button class="loginButton" type="submit">connect</button>
</form>